_format_version: "3.0"

services:
  - name: message-service
    url: http://host.docker.internal:${MESSAGEUCOLAB_PORT}
    routes:
      - name: translate-message-by-code
        paths:
          - ~/messageucolab/v1/messages/[^/]+/translations$
        methods:
          - POST
        regex_priority: 20
        strip_path: false

      - name: messages
        paths:
          - /messageucolab/v1/messages
        methods:
          - GET
          - POST
        strip_path: false

      - name: create-token
        paths:
          - ~/messageucolab/v1/application/[^/]+/token$
        methods:
          - POST
        regex_priority: 10
        strip_path: false

      - name: create-application
        paths:
          - ~/messageucolab/v1/application$
        methods:
          - POST
        regex_priority: 10
        strip_path: false

      - name: catalog
        paths:
          - /messageucolab/v1/catalog
        methods:
          - GET
        strip_path: false

      - name: identity-context
        paths:
          - /messageucolab/v1/me
        methods:
          - GET
          - PUT
        strip_path: false
